
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.1'

target 'toastgo' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'SexyTooltip',:git => 'https://github.com/prscX/SexyTooltip.git'


  # add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  use_native_modules!



  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  # pod 'RNSelectableText', :path => '../node_modules/@astrocoders/react-native-selectable-text/ios/RNSelectableText.podspec'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'toastgoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

	post_install do |installer|
			react_native_post_install(installer)
			installer.pods_project.targets.each do |target|
			  target.build_configurations.each do |config|
			  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
			     end
			end
	end

  target 'Aye!' do
    use_react_native!
  
    pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  end

end
